### ISSUE TITLE
Extension does not work with Calliope mini V3

### ISSUE THREAD

**Issue by fabianhugo** [MKleinSB/pxt-dht11#3]
Thank you for your great work :) 
As you already know the extension currently does not work with the latest mini V3. I was able to reproduce this behaviour with the current makecode.calliope.cc as well as the makecode.microbit.org editors. Interestingly, the extension does also not function if I import it to makecode.microbit.org and use a classic mini. But using it with a classic mini and makecode calliope works well. 

What I also noticed is that the DHT11 extension https://github.com/alankrantas/pxt-dht11_dht22 is still working with the Calliope mini v3 and the latest Calliope makecode editor. Maybe this could hint towards a way how to make it work?

**Comment by MKleinSB** [comment]
Thanks, I will take a look (after the testimonial conferences) and if I have time I try to add software Jacdac, too.

**Comment by MKleinSB** [comment]
Extension is updated. The extension above throws some errors, too. So i changed the waittime a bit. But first values sometimes still are wrong. 
Maybe I should buffer the recieved values for two seconds so that Jacdac can stream. Currently Jacdac doesn´t work. I tried it in https://github.com/MKleinSB/dht11v3 
I think the response of the Sensor is too slow.

**Comment by fabianhugo** [comment]
I did a small test and it looks good now. Thank you!
